version: '3.7'

services:
  db:
    image: mariadb:10.4
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: IVP
      MYSQL_USER: IVP
      MYSQL_PASSWORD: ivp
      MYSQL_ROOT_PASSWORD: ivp
      username: ${username}
      password: ${password}
    network_mode: host
    volumes:
      - "mysql_db:/var/lib/mysql"
      - ./mysql/:/docker-entrypoint-initdb.d/

volumes:
    mysql_db:
